def add(a: int, b: int) -> int:
    """Add two integers."""

def for_loop(start: int, stop: int, step: int, function: function): ...

def sum_range(start: int, stop: int): ...

def print(i: int): ...
